// Adapter + selection for imported puzzle packs (vendor/puzzles/*.json,
// generated by scripts/import-lichess-puzzles.mjs from the CC0 Lichess
// database). Pure data-shaping so the pack pipeline is unit-testable.

// Raw pack entry -> the practice-trainer puzzle shape used by app.js.
// Multi-move puzzles carry solutionLine (player move first, then alternating
// scripted defender replies); the trainer plays the replies automatically.
export function normalizePackPuzzle(raw) {
  if (!raw?.fen || !Array.isArray(raw.solutionLine) || !raw.solutionLine.length) return null;
  const first = raw.solutionLine[0];
  if (typeof first !== "string" || first.length < 4) return null;

  const playerMoves = Math.ceil(raw.solutionLine.length / 2);
  return {
    id: raw.id,
    source: "lichess",
    sourceKey: `lichess:${raw.lichessId || raw.id}`,
    category: raw.category || "candidate_moves",
    rating: Number.isFinite(raw.rating) ? raw.rating : null,
    band: Number.isFinite(raw.band) ? raw.band : 2,
    plainTitle: `Rated ${raw.rating || "?"}`,
    title: `Rated tactic (${raw.rating || "?"})`,
    difficulty: Number.isFinite(raw.band) ? raw.band : 2,
    playerColor: raw.playerColor || raw.fen.split(" ")[1] || "w",
    fen: raw.fen,
    expectedMoves: [first],
    solutionLine: raw.solutionLine,
    targetSquares: [first.slice(2, 4)],
    hintSquares: [first.slice(0, 2)],
    successText: playerMoves > 1
      ? `Solved — you found the full ${playerMoves}-move sequence.`
      : "Solved.",
    missText: "Not that one. Scan the forcing moves: checks, captures, threats.",
    gameUrl: raw.gameUrl || "",
    attribution: "Lichess puzzle (CC0)",
  };
}

// The app's training score (400-1800) mapped onto pack difficulty bands.
export function ratingBandForScore(score) {
  if (!Number.isFinite(score)) return 2;
  if (score < 900) return 1;
  if (score < 1200) return 2;
  if (score < 1500) return 3;
  return 4;
}

// Deterministic pick: unsolved first, then closest difficulty band, then the
// player's biggest weakness categories, then lowest rating for a fair ramp.
export function selectRatedPuzzle(puzzles, {
  score = null,
  solvedKeys = new Set(),
  weaknessCategories = [],
  excludeKey = "",
} = {}) {
  const band = ratingBandForScore(score);
  const weaknessRank = (category) => {
    const index = weaknessCategories.indexOf(category);
    return index === -1 ? weaknessCategories.length : index;
  };

  const pool = (puzzles || []).filter(Boolean).filter((puzzle) => (puzzle.sourceKey || "") !== excludeKey);
  if (!pool.length) return null;

  const ranked = pool
    .map((puzzle) => ({
      puzzle,
      solved: solvedKeys.has(puzzle.sourceKey) ? 1 : 0,
      bandDistance: Math.abs((puzzle.band || 2) - band),
      weakness: weaknessRank(puzzle.category),
    }))
    .sort((a, b) =>
      a.solved - b.solved ||
      a.bandDistance - b.bandDistance ||
      a.weakness - b.weakness ||
      (a.puzzle.rating || 0) - (b.puzzle.rating || 0) ||
      String(a.puzzle.id).localeCompare(String(b.puzzle.id)));

  return ranked[0].puzzle;
}
