// Built-in opening repertoire for the opening trainer. Hand-authored main
// lines of common openings; every move the LEARNER plays carries a `why`.
// Lines are validated for legality by tests/repertoire.test.mjs.

export const REPERTOIRE = [
  {
    id: "italian",
    name: "Italian Game",
    side: "w",
    summary: "Classical development: fast pieces, safe king, fight for the center.",
    lines: [
      {
        id: "italian-giuoco",
        name: "Giuoco Piano main line",
        moves: [
          { san: "e4", why: "Stake a claim in the center and open lines for the bishop and queen." },
          { san: "e5", why: null },
          { san: "Nf3", why: "Develop with a threat — the e5 pawn is attacked at once." },
          { san: "Nc6", why: null },
          { san: "Bc4", why: "Aim the bishop at f7, the weakest square in Black's camp." },
          { san: "Bc5", why: null },
          { san: "c3", why: "Prepare d4 — you want a big center backed by the c-pawn." },
          { san: "Nf6", why: null },
          { san: "d3", why: "Support e4 first. The slow build keeps every piece defended." },
          { san: "d6", why: null },
          { san: "O-O", why: "King safety before adventures. Castling also readies Re1." },
          { san: "O-O", why: null },
          { san: "Re1", why: "Put the rook behind the e-pawn — it fights on the file the game will open." },
          { san: "a6", why: null },
        ],
      },
    ],
  },
  {
    id: "ruy-lopez",
    name: "Ruy Lopez",
    side: "w",
    summary: "Pressure the knight that defends e5 and squeeze for the long game.",
    lines: [
      {
        id: "ruy-closed",
        name: "Closed main line",
        moves: [
          { san: "e4", why: "Take the center and free your pieces." },
          { san: "e5", why: null },
          { san: "Nf3", why: "Attack e5 while developing." },
          { san: "Nc6", why: null },
          { san: "Bb5", why: "Pin pressure: the bishop harasses the defender of e5." },
          { san: "a6", why: null },
          { san: "Ba4", why: "Keep the bishop — the pressure on c6 matters more than a trade." },
          { san: "Nf6", why: null },
          { san: "O-O", why: "Castle first; e4 is tactically poisoned for Black to grab." },
          { san: "Be7", why: null },
          { san: "Re1", why: "Now e4 is truly defended and the center can advance later." },
          { san: "b5", why: null },
          { san: "Bb3", why: "Slide to the strong diagonal — b3 keeps eyeing f7." },
          { san: "d6", why: null },
          { san: "c3", why: "Prepare d4 and give the bishop an escape square on c2." },
          { san: "O-O", why: null },
        ],
      },
    ],
  },
  {
    id: "scotch",
    name: "Scotch Game",
    side: "w",
    summary: "Open the center immediately and develop with tempo.",
    lines: [
      {
        id: "scotch-main",
        name: "Main line",
        moves: [
          { san: "e4", why: "Claim the center." },
          { san: "e5", why: null },
          { san: "Nf3", why: "Develop and attack e5." },
          { san: "Nc6", why: null },
          { san: "d4", why: "Strike now — trade off Black's central pawn before it gets support." },
          { san: "exd4", why: null },
          { san: "Nxd4", why: "Recapture with the knight; it lands on a strong central post." },
          { san: "Nf6", why: null },
          { san: "Nxc6", why: "Damage Black's pawns before they can untangle." },
          { san: "bxc6", why: null },
          { san: "e5", why: "Push the knight around while you own the center." },
          { san: "Qe7", why: null },
          { san: "Qe2", why: "Defend e5 and keep the pin on the e-file working for you." },
          { san: "Nd5", why: null },
          { san: "c4", why: "Kick the knight again — every tempo gained is free development." },
        ],
      },
    ],
  },
  {
    id: "london",
    name: "London System",
    side: "w",
    summary: "A solid setup you can play against almost anything.",
    lines: [
      {
        id: "london-main",
        name: "Standard setup",
        moves: [
          { san: "d4", why: "Take the center on the queenside color." },
          { san: "d5", why: null },
          { san: "Bf4", why: "Develop the bishop OUTSIDE the pawn chain before locking it with e3." },
          { san: "Nf6", why: null },
          { san: "e3", why: "Solidify: the pawn triangle c3-d4-e3 is the London backbone." },
          { san: "c5", why: null },
          { san: "c3", why: "Meet the wing strike calmly — the center holds." },
          { san: "Nc6", why: null },
          { san: "Nd2", why: "This knight supports e4 breaks later and keeps c4 covered." },
          { san: "e6", why: null },
          { san: "Ngf3", why: "Finish kingside development; castling is one move away." },
          { san: "Bd6", why: null },
          { san: "Bg3", why: "Keep the good bishop — trading it would ease Black's game." },
          { san: "O-O", why: null },
          { san: "Bd3", why: "Point the second bishop at the castled king before you castle too." },
        ],
      },
    ],
  },
  {
    id: "vienna",
    name: "Vienna Game",
    side: "w",
    summary: "A sharper cousin of the Italian with early f4 ideas.",
    lines: [
      {
        id: "vienna-main",
        name: "Vienna Gambit accepted",
        moves: [
          { san: "e4", why: "Center first." },
          { san: "e5", why: null },
          { san: "Nc3", why: "Develop while keeping the f-pawn free to advance — the Vienna idea." },
          { san: "Nf6", why: null },
          { san: "f4", why: "The point: strike e5 with a second pawn like a King's Gambit, but safer." },
          { san: "d5", why: null },
          { san: "fxe5", why: "Take the pawn — after ...Nxe4 you gain time on the knight." },
          { san: "Nxe4", why: null },
          { san: "Nf3", why: "Develop and defend against ...Qh4+ ideas." },
          { san: "Be7", why: null },
          { san: "d4", why: "Build the big center your opening promised." },
          { san: "O-O", why: null },
          { san: "Bd3", why: "Challenge the strong e4 knight immediately." },
          { san: "f5", why: null },
          { san: "exf6", why: "Capture en passant — otherwise Black locks your center and keeps the knight forever." },
          { san: "Bxf6", why: null },
        ],
      },
    ],
  },
  {
    id: "qgd",
    name: "Queen's Gambit Declined",
    side: "w",
    summary: "The classical d4 main line: pressure d5 and develop harmoniously.",
    lines: [
      {
        id: "qgd-main",
        name: "Orthodox line",
        moves: [
          { san: "d4", why: "Central control on move one." },
          { san: "d5", why: null },
          { san: "c4", why: "The gambit: challenge d5 to gain central ground — it's not a real sacrifice." },
          { san: "e6", why: null },
          { san: "Nc3", why: "Add a third attacker to d5." },
          { san: "Nf6", why: null },
          { san: "Bg5", why: "Pin the defender of d5 — indirect pressure on the center." },
          { san: "Be7", why: null },
          { san: "e3", why: "Solid structure before finishing development." },
          { san: "O-O", why: null },
          { san: "Nf3", why: "Last minor piece out; you're ready to castle." },
          { san: "h6", why: null },
          { san: "Bh4", why: "Keep the pin. Retreating to h4 maintains all the pressure." },
          { san: "b6", why: null },
          { san: "cxd5", why: "Release the tension at the right moment — after ...b6 the c8 bishop wants b7, so open the position first." },
          { san: "Nxd5", why: null },
        ],
      },
    ],
  },
  {
    id: "qga",
    name: "Queen's Gambit Accepted",
    side: "w",
    summary: "When Black takes c4: reclaim the pawn and enjoy freer development.",
    lines: [
      {
        id: "qga-main",
        name: "Classical line",
        moves: [
          { san: "d4", why: "Center first." },
          { san: "d5", why: null },
          { san: "c4", why: "Offer the gambit pawn to fight for the center." },
          { san: "dxc4", why: null },
          { san: "Nf3", why: "Don't rush to grab c4 back — develop and stop ...e5 first." },
          { san: "Nf6", why: null },
          { san: "e3", why: "Open the bishop's path to recapture on c4." },
          { san: "e6", why: null },
          { san: "Bxc4", why: "Regain the pawn with a developing move — the gambit cost nothing." },
          { san: "c5", why: null },
          { san: "O-O", why: "King safety before the center opens." },
          { san: "a6", why: null },
          { san: "Qe2", why: "Prepare Rd1 and support a later e4 — the queen belongs behind the center." },
          { san: "b5", why: null },
          { san: "Bb3", why: "Keep the bishop on the a2-g8 diagonal where it watches e6 and f7." },
          { san: "Bb7", why: null },
        ],
      },
    ],
  },
  {
    id: "sicilian-open-white",
    name: "Open Sicilian (as White)",
    side: "w",
    summary: "Meet the Sicilian head-on: open the center and develop actively.",
    lines: [
      {
        id: "open-sicilian-najdorf",
        name: "vs Najdorf, Be2 setup",
        moves: [
          { san: "e4", why: "Take the center — against the Sicilian your space advantage starts here." },
          { san: "c5", why: null },
          { san: "Nf3", why: "Develop and prepare d4 — the Open Sicilian promise." },
          { san: "d6", why: null },
          { san: "d4", why: "Open the center; your lead in development is the compensation for the c-file." },
          { san: "cxd4", why: null },
          { san: "Nxd4", why: "Centralize the knight." },
          { san: "Nf6", why: null },
          { san: "Nc3", why: "Defend e4 and complete the classical Sicilian structure." },
          { san: "a6", why: null },
          { san: "Be2", why: "A calm, solid system: develop, castle, then decide on a plan." },
          { san: "e5", why: null },
          { san: "Nb3", why: "Retreat but keep the knight useful — it eyes a5 and c5 squares." },
          { san: "Be7", why: null },
          { san: "O-O", why: "Castle before starting any wing play." },
          { san: "O-O", why: null },
        ],
      },
    ],
  },
  {
    id: "sicilian-najdorf-black",
    name: "Sicilian Najdorf (as Black)",
    side: "b",
    summary: "The most respected fighting defense to 1.e4.",
    lines: [
      {
        id: "najdorf-main",
        name: "English Attack main line",
        moves: [
          { san: "e4", why: null },
          { san: "c5", why: "Fight for d4 from the side — you get an unbalanced game with winning chances." },
          { san: "Nf3", why: null },
          { san: "d6", why: "Control e5 and open the c8 bishop's diagonal." },
          { san: "d4", why: null },
          { san: "cxd4", why: "Trade a wing pawn for a center pawn — a good deal long-term." },
          { san: "Nxd4", why: null },
          { san: "Nf6", why: "Attack e4 immediately; White must spend a move defending." },
          { san: "Nc3", why: null },
          { san: "a6", why: "The Najdorf move: stops Bb5+ and Nb5, prepares ...e5 and ...b5." },
          { san: "Be3", why: null },
          { san: "e5", why: "Kick the strong d4 knight and grab central space — d6 stays solid." },
          { san: "Nb3", why: null },
          { san: "Be6", why: "Develop toward the center and keep an eye on White's c4 ideas." },
          { san: "f3", why: null },
          { san: "Be7", why: "Finish development; castling next. Your play comes on the queenside." },
        ],
      },
    ],
  },
  {
    id: "french",
    name: "French Defense",
    side: "b",
    summary: "A solid pawn chain and a clear plan: strike the center with ...c5.",
    lines: [
      {
        id: "french-winawer",
        name: "Winawer main line",
        moves: [
          { san: "e4", why: null },
          { san: "e6", why: "Prepare ...d5 with full support — solidity first." },
          { san: "d4", why: null },
          { san: "d5", why: "Challenge e4 immediately. This is the French point." },
          { san: "Nc3", why: null },
          { san: "Bb4", why: "The Winawer: pin the knight so e4 really is attacked." },
          { san: "e5", why: null },
          { san: "c5", why: "Hit the pawn chain at its base — your standard French break." },
          { san: "a3", why: null },
          { san: "Bxc3+", why: "Give up the bishop to wreck White's queenside pawns." },
          { san: "bxc3", why: null },
          { san: "Ne7", why: "Develop toward f5/g6; the knight also guards your kingside." },
          { san: "Qg4", why: null },
          { san: "Qc7", why: "Defend indirectly: cover e5 ideas and eye c3 — don't panic about g7." },
        ],
      },
    ],
  },
  {
    id: "caro-kann",
    name: "Caro-Kann Defense",
    side: "b",
    summary: "Solid like the French, but your light-squared bishop gets out first.",
    lines: [
      {
        id: "caro-classical",
        name: "Classical main line",
        moves: [
          { san: "e4", why: null },
          { san: "c6", why: "Prepare ...d5 while keeping the c8 bishop's diagonal open." },
          { san: "d4", why: null },
          { san: "d5", why: "Challenge the center with full support." },
          { san: "Nc3", why: null },
          { san: "dxe4", why: "Trade in the center — your structure stays rock solid." },
          { san: "Nxe4", why: null },
          { san: "Bf5", why: "The Caro point: develop this bishop BEFORE playing ...e6 locks it in." },
          { san: "Ng3", why: null },
          { san: "Bg6", why: "Keep the bishop safe on the long diagonal edge." },
          { san: "h4", why: null },
          { san: "h6", why: "Give the bishop an escape square before White traps it with h5." },
          { san: "Nf3", why: null },
          { san: "Nd7", why: "Develop and prepare ...Ngf6 without allowing doubled pawns." },
          { san: "h5", why: null },
          { san: "Bh7", why: "Tuck the bishop away — it still watches the b1-h7 diagonal." },
        ],
      },
    ],
  },
  {
    id: "kings-indian",
    name: "King's Indian Defense",
    side: "b",
    summary: "Concede the center, then attack it — and the king — with pawns.",
    lines: [
      {
        id: "kid-main",
        name: "Classical main line",
        moves: [
          { san: "d4", why: null },
          { san: "Nf6", why: "Flexible development — commit the pawns later." },
          { san: "c4", why: null },
          { san: "g6", why: "Prepare the fianchetto: the g7 bishop is your best piece." },
          { san: "Nc3", why: null },
          { san: "Bg7", why: "The King's Indian bishop — it will pressure the center for the whole game." },
          { san: "e4", why: null },
          { san: "d6", why: "Restrain e5 and open the c8 bishop. Let White build the big center." },
          { san: "Nf3", why: null },
          { san: "O-O", why: "Castle before the central fight starts." },
          { san: "Be2", why: null },
          { san: "e5", why: "The counter-strike: hit d4 now that your king is safe." },
          { san: "O-O", why: null },
          { san: "Nc6", why: "Add pressure on d4 and provoke d5." },
          { san: "d5", why: null },
          { san: "Ne7", why: "The center is locked: now your plan is ...f5 and a kingside pawn storm." },
        ],
      },
    ],
  },
];

export function getOpeningById(id) {
  return REPERTOIRE.find((opening) => opening.id === id) || null;
}

export function getLineById(lineId) {
  for (const opening of REPERTOIRE) {
    const line = opening.lines.find((item) => item.id === lineId);
    if (line) return { opening, line };
  }
  return null;
}

// Plies the learner plays in a line (0-indexed): even plies for white, odd for black.
export function learnerPlaysAt(side, plyIndex) {
  return side === "w" ? plyIndex % 2 === 0 : plyIndex % 2 === 1;
}
